### ISSUE TITLE
Stream Processor has Stopped

### ISSUE THREAD

**Issue by twhnat** [MD2Korg/mCerebrum-StreamProcessor#2]
_From @DanielaGarza on April 4, 2016 16:50_

Phone configured for PF3
Time: 10:30 - 11:45 multiple notifications 
Notification that "Stream processor has stopped"
ECG data reading straight line at the top.

_Copied from original issue: MD2Korg/stream-processor#60_

**Comment by twhnat** [comment]
@DanielaGarza This is good to know.  Please confirm that the stream processor functions correctly with a proper ECG signal.

**Comment by DanielaGarza** [comment]
Yes, it is working now!
